import debug from 'debug';
const debugLogger = debug('joke3:server');

import express from 'express';

//validate input
import Ajv from 'ajv';
const ajv = new Ajv();
import addSanitizers from 'ajv-sanitizer';
addSanitizers(ajv);

import {appointmentAjvSchema, getAttendeesAjvSchema, changeVisibilityAjvSchema} from '../api/shemas.mjs';

const validate = ajv.compile(appointmentAjvSchema);

const validate_getAttendees = ajv.compile(getAttendeesAjvSchema);

const validate_vis = ajv.compile(changeVisibilityAjvSchema);

// mongodb
import {
    getAppointments,
    createAppointment,
    getPublicAppointments,
    getPublicAndOwnAppointments, getAttending, changeVis
} from "../service/calenderService.mjs";

const router = express.Router();

// Swagger comment Generated by chatGPT
/**
 * @swagger
 * /api/private/:
 *   get:
 *     summary: Get all appointments
 *     description: Returns a list of all public and own appointments stored in the database.
 *     tags:
 *       - Appointments
 *     responses:
 *       200:
 *         description: Successfully retrieved appointments
 *         content:
 *           application/json:
 *             schema:
 *               type: array
 *               items:
 *                 type: object
 *                 properties:
 *                   _id:
 *                     type: string
 *                     example: "64f1a9c2b8a1c123456789ab"
 *                   date:
 *                     type: string
 *                     example: "2025-12-18"
 *                   title:
 *                     type: string
 *                     example: "Team Meeting"
 *                   description:
 *                     type: string
 *                     example: "Weekly project sync"
 *       500:
 *         description: Failed to query appointments
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 error:
 *                   type: string
 *                   example: "Failed to query appointments"
 */
router.get('/', async function (req, res) {
    try {
        const all_appos = await getPublicAndOwnAppointments(req.user.email);

        return res.status(200).json(all_appos);
    }
    catch (error){
        return res.status(500).json({ error: 'Failed to query appointments: ' + error.message });
    }
});

// Swagger comment Generated by chatGPT
// Swagger comment Generated by chatGPT
/**
 * @swagger
 * /api/private/username:
 *   get:
 *     summary: Get the authenticated user's email
 *     description: |
 *       Returns the email address (username) of the currently authenticated user.
 *       This endpoint is only accessible for authenticated users.
 *     tags:
 *       - Authentication
 *     security:
 *       - cookieAuth: []
 *     responses:
 *       200:
 *         description: Successfully returned the authenticated user's email
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 username:
 *                   type: string
 *                   example: user@example.com
 *       401:
 *         description: Unauthorized – user is not authenticated
 *       500:
 *         description: Server error
 */
router.get('/username', async function (req, res) {
    return res.status(200).json({username: req.user.email});
});

// Swagger comment Generated by chatGPT
/**
 * @swagger
 * /api/private/ping:
 *   get:
 *     summary: Ping the private API
 *     description: |
 *       Simple health check endpoint for the private API.
 *       Returns a JSON object `{ ping: "true" }` to indicate the server is reachable.
 *     tags:
 *       - Health
 *     responses:
 *       200:
 *         description: Server is reachable
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 ping:
 *                   type: string
 *                   example: "true"
 *       401:
 *         description: Unauthorized access
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 error:
 *                   type: string
 *                   example: "Unauthorized"
 *       500:
 *         description: Server error
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 error:
 *                   type: string
 *                   example: "Internal server error"
 */
router.get('/ping', async function (req, res) {
    return res.status(200).json({ping: "true"});
});

// Swagger comment generated by chatGPT
/**
 * @swagger
 * /api/private/create:
 *   post:
 *     summary: Create a new appointment
 *     description: |
 *       Creates a new appointment.
 *       The fields `id` and `attending` are generated automatically and must NOT be provided by the client.
 *     tags:
 *       - Appointments
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             required:
 *               - title
 *               - description
 *               - date
 *               - time
 *               - location
 *               - deadline
 *               - visibility
 *               - max_attending
 *             properties:
 *               title:
 *                 type: string
 *                 example: "Project Kickoff"
 *               description:
 *                 type: string
 *                 example: "Kickoff of the new calender management system"
 *               date:
 *                 type: string
 *                 example: "2025-12-18"
 *               time:
 *                 type: string
 *                 example: "10:00"
 *               location:
 *                 type: string
 *                 example: "Conference Room A"
 *               deadline:
 *                 type: string
 *                 example: "2025-12-15"
 *               max_attending:
 *                 type: number
 *                 example: 50
 *               visibility:
 *                 type: string
 *                 enum: [private, unlisted, public]
 *     responses:
 *       201:
 *         description: Appointment successfully created
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 id:
 *                   type: string
 *                   example: "AbCdEfGhIjKlMnOpQrStUvWxY"
 *                 title:
 *                   type: string
 *                 description:
 *                   type: string
 *                 date:
 *                   type: string
 *                 time:
 *                   type: string
 *                 location:
 *                   type: string
 *                 deadline:
 *                   type: string
 *                 visibility:
 *                   type: string
 *                 owner:
 *                   type: string
 *                 max_attending:
 *                   type: number
 *                 attending:
 *                   type: array
 *                   items:
 *                     type: object
 *       400:
 *         description: Missing or invalid request body
 *       422:
 *         description: Validation failed
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 error:
 *                   type: string
 *                 details:
 *                   type: array
 *       500:
 *         description: Failed to save the appointment
 */
router.post('/create', async (req, res) => {
    const new_data = req.body;

    if (!new_data ) {
        return res.status(400).json({error: 'object missing'});
    }
    if (typeof new_data !== 'object') {
        return res.status(400).json({error: `Invalid appointment data format: ${typeof new_data}`});
    }

    const valid = validate(new_data);

    if (!valid) {
        return res.status(422).json({
            error: 'Validation failed',
            details: validate.errors
        });
    }

    // Add the owner
    new_data["owner"] = req.user.email;

    try {
        const saved_data = await createAppointment(new_data);
        return res.status(201).json(saved_data);
    }
    catch (err) {
        debugLogger('Error saving appointment:', {
            message: err.message,
            stack: err.stack,
            input: new_data
        });
        return res.status(500).json({ error: 'Failed to save the appointment: ' + err.message });
    }
})

// Swagger comment generated by chatGPT
/**
 * @swagger
 * /api/private/attending:
 *   post:
 *     summary: Get attendees of an appointment
 *     description: |
 *       Returns the list of attendees for a specific appointment.
 *       The request must include the `appointmentID`.
 *       Only authenticated users can access this endpoint.
 *     tags:
 *       - Appointments
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             required:
 *               - appointmentID
 *             properties:
 *               appointmentID:
 *                 type: string
 *                 minLength: 25
 *                 maxLength: 25
 *                 pattern: "^[A-Za-z]{25}$"
 *                 example: "AbCdEfGhIjKlMnOpQrStUvWxY"
 *                 description: The unique ID of the appointment
 *     responses:
 *       201:
 *         description: List of attendees returned successfully
 *         content:
 *           application/json:
 *             schema:
 *               type: array
 *               items:
 *                 type: object
 *                 properties:
 *                   email:
 *                     type: string
 *                     example: "bob@example.com"
 *                   first_name:
 *                     type: string
 *                     example: "Bob"
 *                   last_name:
 *                     type: string
 *                     example: "Smith"
 *       400:
 *         description: Missing or invalid request body
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 error:
 *                   type: string
 *                   example: "object missing"
 *       422:
 *         description: Validation failed
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 error:
 *                   type: string
 *                 details:
 *                   type: array
 *       500:
 *         description: Failed to retrieve attendees
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 error:
 *                   type: string
 *                   example: "Failed: Appointment not found"
 */
router.post('/attending', async (req, res) => {
    const new_data = req.body;

    if (!new_data ) {
        return res.status(400).json({error: 'object missing'});
    }
    if (typeof new_data !== 'object') {
        return res.status(400).json({error: `Invalid data format: ${typeof new_data}`});
    }

    const valid = validate_getAttendees(new_data);

    if (!valid) {
        return res.status(422).json({
            error: 'Validation failed',
            details: validate.errors
        });
    }

    try {
        const list = await getAttending(new_data.appointmentID, req.user.email);
        return res.status(201).json(list);
    }
    catch (err) {
        return res.status(500).json({ error: 'Failed: ' + err.message });
    }
})

// Swagger comment generated by chatGPT
/**
 * @swagger
 * /api/private/change-visibility:
 *   post:
 *     summary: Change appointment visibility
 *     description: |
 *       Changes the visibility of an existing appointment.
 *       The appointment is identified by its unique ID.
 *     tags:
 *       - Appointments
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             required:
 *               - appointmentID
 *               - visibility
 *             properties:
 *               appointmentID:
 *                 type: string
 *                 description: Unique ID of the appointment
 *                 example: "AbCdEfGhIjKlMnOpQrStUvWxY"
 *               visibility:
 *                 type: string
 *                 description: New visibility setting
 *                 enum: [private, unlisted, public]
 *     responses:
 *       201:
 *         description: Visibility successfully updated
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 request:
 *                   type: string
 *                   example: "ok"
 *       400:
 *         description: Missing or invalid request body
 *       422:
 *         description: Validation failed
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 error:
 *                   type: string
 *                 details:
 *                   type: array
 *       500:
 *         description: Failed to change appointment visibility
 */

router.post('/change-visibility', async (req, res) => {
    const new_data = req.body;

    if (!new_data ) {
        return res.status(400).json({error: 'object missing'});
    }
    if (typeof new_data !== 'object') {
        return res.status(400).json({error: `Invalid request format: ${typeof new_data}`});
    }

    const valid = validate_vis(new_data);

    if (!valid) {
        return res.status(422).json({
            error: 'Validation failed',
            details: validate.errors
        });
    }

    try {
        await changeVis(new_data.appointmentID, new_data.visibility, req.user.email);
        return res.status(201).json({request: 'ok'});
    }
    catch (err) {
        return res.status(500).json({ error: 'Error in request: ' + err.message });
    }
})

export default router;