import express from 'express';

// mongodb
import {
    getAppointments,
    createAppointment,
    getPublicAppointments,
    signOn,
    getPublicAndOwnAppointments
} from "../service/calenderService.mjs";

import AppointmentModel from '../models/calenderModel.mjs';

//validate input
import Ajv from 'ajv';
const ajv = new Ajv();
import addSanitizers from 'ajv-sanitizer';
addSanitizers(ajv);

import {signOnAjvSchema, getAttendeesAjvSchema} from '../api/shemas.mjs';

const validate = ajv.compile(signOnAjvSchema);
const validate_get_single = ajv.compile(getAttendeesAjvSchema);

const router = express.Router();

// Swagger comment Generated by chatGPT
/**
 * @swagger
 * /api/public/:
 *   get:
 *     summary: Get all appointments
 *     description: Returns a list of all public appointments stored in the database.
 *     tags:
 *       - Appointments
 *     responses:
 *       200:
 *         description: Successfully retrieved appointments
 *         content:
 *           application/json:
 *             schema:
 *               type: array
 *               items:
 *                 type: object
 *                 properties:
 *                   _id:
 *                     type: string
 *                     example: "64f1a9c2b8a1c123456789ab"
 *                   date:
 *                     type: string
 *                     example: "2025-12-18"
 *                   title:
 *                     type: string
 *                     example: "Team Meeting"
 *                   description:
 *                     type: string
 *                     example: "Weekly project sync"
 *       500:
 *         description: Failed to query appointments
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 error:
 *                   type: string
 *                   example: "Failed to query appointments"
 */
router.get('/', async function (req, res) {
    try {
        const all_appos = await getPublicAppointments();

        return res.status(200).json(all_appos);
    }
    catch (error){
        return res.status(500).json({ error: 'Failed to query appointments' });
    }
})

// Swagger comment generated by chatGPT
/**
 * @swagger
 * /api/public/signon:
 *   post:
 *     summary: Sign on to an appointment
 *     description: Adds an attendee to an appointment. The appointment is identified by its `appointmentID`.
 *                  The attendee's email, first name, and last name are provided in the request body.
 *     tags:
 *       - Appointments
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             required:
 *               - appointmentID
 *               - email
 *               - first_name
 *               - last_name
 *             properties:
 *               appointmentID:
 *                 type: string
 *                 minLength: 25
 *                 maxLength: 25
 *                 pattern: "^[A-Za-z]{25}$"
 *                 example: "AbCdEfGhIjKlMnOpQrStUvWxY"
 *                 description: Unique ID of the appointment
 *               email:
 *                 type: string
 *                 format: email
 *                 example: "bob@example.com"
 *               first_name:
 *                 type: string
 *                 example: "Bob"
 *               last_name:
 *                 type: string
 *                 example: "Smith"
 *     responses:
 *       201:
 *         description: Attendee successfully signed on
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 request:
 *                   type: string
 *                   example: "ok"
 *       400:
 *         description: Missing or invalid request body
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 error:
 *                   type: string
 *                   example: "object missing"
 *       422:
 *         description: Validation failed
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 error:
 *                   type: string
 *                 details:
 *                   type: array
 *                   items:
 *                     type: object
 *       500:
 *         description: Server error while signing on
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 error:
 *                   type: string
 *                   example: "Error in request: Appointment not found"
 */
router.post('/signon', async (req, res) => {
    const new_data = req.body;

    if (!new_data ) {
        return res.status(400).json({error: 'object missing'});
    }
    if (typeof new_data !== 'object') {
        return res.status(400).json({error: `Invalid sign on request format: ${typeof new_data}`});
    }

    const valid = validate(new_data);

    if (!valid) {
        return res.status(422).json({
            error: 'Validation failed',
            details: validate.errors
        });
    }

    try {
        await signOn(
            new_data.appointmentID,
            new_data.email,
            new_data.first_name,
            new_data.last_name
        );
        return res.status(201).json({request: 'ok'});
    }
    catch (err) {
        return res.status(500).json({ error: 'Error in request: ' + err.message });
    }
})

// Swagger comment generated by chatGPT
// Swagger comment generated by ChatGPT
/**
 * @swagger
 * /api/public/get-single:
 *   post:
 *     summary: Get a single appointment by ID
 *     description: |
 *       Returns the appointment with the specified ID.
 *       - Public appointments are visible to everyone.
 *       - Unlisted appointments are visible to anyone who has the ID.
 *       - Private appointments are only visible to the owner (requires authentication).
 *     tags:
 *       - Appointments
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             required:
 *               - appointmentID
 *             properties:
 *               appointmentID:
 *                 type: string
 *                 description: The unique ID of the appointment to fetch
 *                 example: "AbCdEfGhIjKlMnOpQrStUvWxY"
 *     responses:
 *       200:
 *         description: Appointment found
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 id:
 *                   type: string
 *                 title:
 *                   type: string
 *                 date:
 *                   type: string
 *                 time:
 *                   type: string
 *                 location:
 *                   type: string
 *                 deadline:
 *                   type: string
 *                 visibility:
 *                   type: string
 *                 owner:
 *                   type: string
 *                 attending:
 *                   type: array
 *                   items:
 *                     type: object
 *       400:
 *         description: Missing or invalid request body
 *       422:
 *         description: Validation failed
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 error:
 *                   type: string
 *                 details:
 *                   type: array
 *       404:
 *         description: Appointment not found or access denied
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 error:
 *                   type: string
 *       500:
 *         description: Server error
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 error:
 *                   type: string
 */
router.post('/get-single', async (req, res) => {
    const new_data = req.body;

    if (!new_data) {
        return res.status(400).json({ error: 'object missing' });
    }
    if (typeof new_data !== 'object') {
        return res.status(400).json({ error: `Invalid request format: ${typeof new_data}` });
    }

    const valid = validate_get_single(new_data);
    if (!valid) {
        return res.status(422).json({
            error: 'Validation failed',
            details: validate_get_single.errors
        });
    }

    try {
        let query = { id: new_data.appointmentID };

        if (req.isAuthenticated()) {
            query = {
                id: new_data.appointmentID,
                $or: [
                    { visibility: { $in: ['public', 'unlisted'] } },
                    { owner: req.user.email }  // include private if owner
                ]
            };
        } else {
            query = {
                id: new_data.appointmentID,
                visibility: { $in: ['public', 'unlisted'] }
            };
        }

        const appointment = await AppointmentModel.findOne(query).exec();

        if (!appointment) {
            return res.status(404).json({ error: 'Appointment not found' });
        }

        return res.status(200).json(appointment);

    } catch (err) {
        return res.status(500).json({ error: 'Error in request: ' + err.message });
    }
});



export default router;